<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "usermynews"
 *
 * Auto generated by Extension Builder 2014-09-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'User My News',
	'description' => 'It contains listing of news and detail page.',
	'category' => 'plugin',
	'author' => 'Mohsin Abbas',
	'author_email' => 'mohsinpucit@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);